apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ruq5ydbte-go 
  janus-idp.io/tekton: ruq5ydbte-go
  backstage.io/kubernetes-id: ruq5ydbte-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ruq5ydbte-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  