apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ruq5ydbte-go
  janus-idp.io/tekton: ruq5ydbte-go
  backstage.io/kubernetes-id: ruq5ydbte-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ruq5ydbte-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
