apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ruq5ydbte-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ruq5ydbte-go 
  name: ruq5ydbte-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ruq5ydbte-go 
